export enum BusinessType {
  SERVICE = 'SERVICE',
  CONSTRUCTION = 'CONSTRUCTION',
  RETAIL = 'RETAIL',
  COSMETIC = 'COSMETIC',
  OTHER = 'OTHER',
}

export enum BusinessFocus {
  FINANCIAL_CASH = 'FINANCIAL_CASH',
  BUSINESS_GROWTH_HEALTH = 'BUSINESS_GROWTH_HEALTH',
  FORECASTING_PLANNING = 'FORECASTING_PLANNING',
  METRICS_INSIGHTS = 'METRICS_INSIGHTS',
  PRODUCT_MARKET_FIT = 'PRODUCT_MARKET_FIT',
}
